"""this script reads in several csv files and cleans them up to 
be used in the model

CSVs live in the model_inputs_29102025 subfolder of this project

CSVs to read in:

- model_inputs_29102025/model_power_29102025.csv
- model_inputs_29102025/model_gxp_info_29102025.csv
- model_inputs_29102025/reserve_prices_29102025.csv
- 
   

"""

### the goal is to create a single dataframe that is used in the model
### the dataframe should have the following columns:
"""
- tradinginterval: the datetime of the power generation, in this format: 2024-05-26T00:00:00.000+12:00.
- trading_period: the trading period used in the reserve market, 
    1-48 for each 30 minute period in the day
- node: the cod of the node in the list above (GFD0331, GYT0331, HAY0111, HAY0331, MLG0111, MLG0331, MST0331, PNI0331, TKR0331, UHT0331)
- load: the load at the node in kw
- power_generated: the power generated by the generator.
- price_gxp: the price of electricity at the closest grid exchange point.
- price_6sec: the price of electricity at the 6-second interval.
- price_60sec: the price of electricity at the 60-second interval. """

"""you need to read in the model_power_29102025.csv file first
then read in model_gxp_info_29102025.csv file
then read in reserve_prices_29102025.csv file
then create a new dataframe that combines the three dataframes, called
complete_model_inputs_29102025
and save it as a csv file to the model_inputs_29102025 subfolder of this project

"""

f"""
we need all the columns from the model_power_29102025.csv file
we need the following columns from the model_gxp_info_29102025.csv file:
1) LoadMegawatts	
2) DollarsPerMegawattHour
3) TradingPeriodNumber
you should be able to join the two dataframes on the node and the tradinginterval columns
IntervalDateTime is the name used in the model_gxp_info_29102025.csv file and tradinginterval
is used in the model_power_29102025.csv file
PointOfConnectionCode in the model_gxp_info_29102025.csv file is the same 
as node in the model_power_29102025.csv file

then subset the reserve_prices_29102025.csv file to only include 
1) rows where Region ID equals NI
2) the trading period column
3) the dd/mm/yyyy part of the Period start column
4) FIR price ($/MWh) - rename this to price_6sec
5) SIR price ($/MWh) - rename this to price_60sec

join the subsetted reserve_prices_29102025.csv file to the complete_model_inputs_29102025 dataframe
using both the trading period column which is the same as tradingperiodnumber in
the model_gxp_info_29102025.csv file and the dd/mm/yyyy part of the Period start
from the reserve_prices_29102025.csv file which should match the
 tradinginterval column after you have converted it to yyyy/mm/dd format

"""

### gpt 5 output

"""Build a single dataframe for the model from three CSV inputs.

Inputs (under model_inputs_29102025/):
- model_power_29102025.csv (5-min, per node)
- model_gxp_info_29102025.csv (5-min, per node)
- reserve_prices_29102025.csv (30-min, NI subset used)

Output:
- complete_model_inputs_29102025.csv with columns:
  tradinginterval, trading_period (1-48), node, load (kW),
  power_generated (kW), price_gxp ($/MWh), price_6sec ($/MWh), price_60sec ($/MWh)
"""

from pathlib import Path
import pandas as pd


INPUT_DIR = Path(__file__).parent / "model_inputs_29102025"
OUTPUT_FILE = INPUT_DIR / "complete_model_inputs_29102025.csv"


def read_inputs():
    power_path = INPUT_DIR / "model_power_29102025.csv"
    gxp_path = INPUT_DIR / "model_gxp_info_29102025.csv"
    reserve_path = INPUT_DIR / "reserve_prices_29102025.csv"

    df_power = pd.read_csv(power_path)
    # Parse tradinginterval (ISO with tz OK); keep timezone if present
    df_power["tradinginterval"] = pd.to_datetime(
        df_power["tradinginterval"], errors="coerce", utc=True
    )
    # Standardize expected column names from power CSV
    if "power" in df_power.columns:
        df_power = df_power.rename(columns={"power": "power_generated"})

    df_gxp = pd.read_csv(gxp_path)
    if "IntervalDateTime" in df_gxp.columns:
        df_gxp["IntervalDateTime"] = pd.to_datetime(
            df_gxp["IntervalDateTime"], errors="coerce", utc=True
        )

    df_res = pd.read_csv(reserve_path)

    return df_power, df_gxp, df_res


def join_power_with_gxp(df_power: pd.DataFrame, df_gxp: pd.DataFrame) -> pd.DataFrame:
    # Required columns from GXP
    needed_cols = [
        "IntervalDateTime",
        "PointOfConnectionCode",
        "LoadMegawatts",
        "DollarsPerMegawattHour",
        "TradingPeriodNumber",
    ]
    missing = [c for c in needed_cols if c not in df_gxp.columns]
    if missing:
        raise KeyError(f"model_gxp_info_29102025.csv missing columns: {missing}")

    gxp_sel = df_gxp[needed_cols].copy()

    # Merge on node and timestamp equality (both at 5-minute granularity)
    merged = df_power.merge(
        gxp_sel,
        left_on=["node", "tradinginterval"],
        right_on=["PointOfConnectionCode", "IntervalDateTime"],
        how="left",
    )

    # Requested columns
    merged["trading_period"] = merged["TradingPeriodNumber"].astype("Int64")
    merged["load"] = (merged["LoadMegawatts"] * 1000).astype("float")
    merged["price_gxp"] = merged["DollarsPerMegawattHour"].astype("float")
    return merged


def prep_reserve_prices(df_res: pd.DataFrame) -> pd.DataFrame:
    # Keep NI and required columns
    # Normalize common header variant: "Trading period" vs "Trading Period"
    if "Trading Period" not in df_res.columns:
        for alt in ["Trading period", "trading period", "TRADING PERIOD"]:
            if alt in df_res.columns:
                df_res = df_res.rename(columns={alt: "Trading Period"})
                break
    required_cols = [
        "Region ID",
        "Trading Period",
        "Period start",
        "FIR price ($/MWh)",
        "SIR price ($/MWh)",
    ]
    missing = [c for c in required_cols if c not in df_res.columns]
    if missing:
        raise KeyError(f"reserve_prices_29102025.csv missing columns: {missing}")

    df_res = df_res[df_res["Region ID"] == "NI"].copy()
    df_res = df_res[[
        "Trading Period",
        "Period start",
        "FIR price ($/MWh)",
        "SIR price ($/MWh)",
    ]].copy()

    # Parse Period start to date key (dd/mm/yyyy handled via dayfirst)
    df_res["Period start"] = pd.to_datetime(
        df_res["Period start"], errors="coerce", dayfirst=True
    )
    df_res["date"] = df_res["Period start"].dt.date

    # Rename for alignment
    df_res = df_res.rename(columns={
        "Trading Period": "TradingPeriodNumber",
        "FIR price ($/MWh)": "price_6sec",
        "SIR price ($/MWh)": "price_60sec",
    })

    return df_res[["date", "TradingPeriodNumber", "price_6sec", "price_60sec"]]


def main():
    df_power, df_gxp, df_res = read_inputs()

    # Merge power (5-min) with GXP (5-min) on node + timestamp
    combined = join_power_with_gxp(df_power, df_gxp)

    # Prepare NI reserve prices (30-min) and join on date + trading period
    res_prepped = prep_reserve_prices(df_res)
    # Use local NZ date for joining to reserve data (which is by local day + TP)
    combined["date"] = combined["tradinginterval"].dt.tz_convert("Pacific/Auckland").dt.date
    combined = combined.merge(
        res_prepped,
        left_on=["date", "TradingPeriodNumber"],
        right_on=["date", "TradingPeriodNumber"],
        how="left",
    )

    # Final selection and ordering
    final_cols = [
        "tradinginterval",
        "trading_period",
        "node",
        "load",
        "power_generated",
        "price_gxp",
        "price_6sec",
        "price_60sec",
    ]

    # Ensure node exists
    if "node" not in combined.columns and "PointOfConnectionCode" in combined.columns:
        combined["node"] = combined["PointOfConnectionCode"]

    # Coerce reserves to numeric
    for col in ["price_6sec", "price_60sec"]:
        if col in combined.columns:
            combined[col] = pd.to_numeric(combined[col], errors="coerce")

    out = combined[final_cols].copy()

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(OUTPUT_FILE, index=False)


if __name__ == "__main__":
    main()

 
