import pulp
import pandas as pd
from typing import Optional

## #parameters
## from the raw data csv file
# price_gxp: The price of electricity at the closest grid exchange point.
# price_6sec: The price of electricity at the 6-second interval.
# price_60sec: The price of electricity at the 60-second interval.
# p_w: The power generated by the generator.
# p_w_bar: the max power generated in a period.
# p_w_underline: the min power generated in a period.

## set by the user

# time_periods: The number of time periods in the horizon.
# battery: The number of batteries in the system.
# E_0: The initial energy in the battery.
# E_max: The max energy in the battery.
# E_min: The min energy in the battery.
# eta_ch: The efficiency of the charger.
# eta_dis: The efficiency of the discharger.
# DR_bar: The max power discharged in a period.
# CR_bar: The max power charged in a period.
# lamda_bat: The degradation cost of the battery.
# D: The time step.
# M: a numeric variable to do big M constraints.

## calculated using the functions in this file
# e_da: the energy traded in the spot market.
# e_b_da: the energy bought from the spot market.
# e_s_da: the energy sold to the spot market.
# J_s: whether the generator is a buyer or a seller in the spot market. (1 if buyer, -1 if seller)
# e_6sec: the energy traded in the 6-second interval reserve market.
# e_60sec: the energy traded in the 60-second interval reserve market.
# e_ch: the energy charged to the battery.
# e_da_dis: the energy discharged from the battery in the spot market.
# e_6sec_dis: the energy discharged from the battery in the 6-second interval reserve market.
# e_60sec_dis: the energy discharged from the battery in the 60-second interval reserve market.
# u_ch: whether the battery is charging or discharging. (1 if charging, 0 if discharging)
# e_soc: the state of charge of the battery.
# cost_deg: the degradation cost of the battery.
# E_dem: the total energy demand of the battery.
# e_cap_underline: the min energy capacity of the battery.
# e_cap_bar: the max energy capacity of the battery.






def build_generator_schedule(params):
    """
    Build the deterministic generator scheduling optimization model using PuLP.

    Parameters
    ----------
    params : dict
        Dictionary containing all model parameters, sets, and scalars.

    Returns
    -------
    tuple[pulp.LpProblem, dict]
        The constructed PuLP model and a dictionary of decision variables.
    """
    # Unpack sets
    time_periods = params["time_periods"]
    battery = params["battery"]

    # Unpack parameters
    price_gxp = params["price_gxp"]
    price_6sec = params["price_6sec"]
    price_60sec = params["price_60sec"]
    

    
    call = params["call"]

    p_w = params["p_w"]
    p_w_bar = params["p_w_bar"]
    p_w_underline = params["p_w_underline"]
    E_0 = params["E_0"]
    E_max = params["E_max"]
    E_min = params["E_min"]
    eta_ch = params["eta_ch"]
    eta_dis = params["eta_dis"]
    DR_bar = params["DR_bar"]
    CR_bar = params["CR_bar"]
    lamda_bat = params["lamda_bat"]
    

    M = params.get("M", 10000)
    D = params.get("D", 1)
    e_da_max = params.get("e_da_max", 100)

    # Create model
    model = pulp.LpProblem("generator_Deterministic_Scheduling", pulp.LpMaximize)

    # Decision variables
    e_da = pulp.LpVariable.dicts("e_da", time_periods, cat="Continuous")
    e_s_da = pulp.LpVariable.dicts("e_s_da", time_periods, lowBound=0, cat="Continuous")
    e_b_da = pulp.LpVariable.dicts("e_b_da", time_periods, upBound=0, cat="Continuous")
    J_s = pulp.LpVariable.dicts("J_s", time_periods, cat="Binary")

    e_6sec = pulp.LpVariable.dicts("e_6sec", time_periods, lowBound=0, cat="Continuous")
    e_60sec = pulp.LpVariable.dicts("e_60sec", time_periods, lowBound=0, cat="Continuous")

    e_ch = pulp.LpVariable.dicts("e_ch", (battery, time_periods), lowBound=0, cat="Continuous")
    e_da_dis = pulp.LpVariable.dicts("e_da_dis", (battery, time_periods), lowBound=0, cat="Continuous")
    e_6sec_dis = pulp.LpVariable.dicts("e_6sec_dis", (battery, time_periods), lowBound=0, cat="Continuous")
    e_60sec_dis = pulp.LpVariable.dicts("e_60sec_dis", (battery, time_periods), lowBound=0, cat="Continuous")
    u_ch = pulp.LpVariable.dicts("u_ch", (battery, time_periods), cat="Binary")
    e_soc = pulp.LpVariable.dicts("e_soc", (battery, time_periods), lowBound=0, cat="Continuous")

    cost_deg = pulp.LpVariable.dicts("cost_deg", (battery, time_periods), lowBound=0, cat="Continuous")
    # Endogenous total energy over horizon per battery (was a parameter; now a variable)
    E_dem = pulp.LpVariable.dicts("E_dem", battery, lowBound=0, cat="Continuous")

    # Objective: maximize total profit
    model += (
        # DA net revenue; e_da[t] is energy (kWh), so no D factor here.
        pulp.lpSum([price_gxp[t] * e_da[t] for t in time_periods])
        + pulp.lpSum([call[t] * price_6sec[t] * e_6sec[t] for t in time_periods])
        + pulp.lpSum([call[t] * price_60sec[t] * e_60sec[t] for t in time_periods])
        - pulp.lpSum([cost_deg[n][t] for n in battery for t in time_periods])
        
    ), "Total_Profit"

    # Constraints
    # generator energy balance
    for t in time_periods:
        model += e_da[t] == p_w[t] * D + pulp.lpSum(
            [
                (e_da_dis[n][t] + e_6sec_dis[n][t] + e_60sec_dis[n][t]) * eta_dis
                - e_ch[n][t] / eta_ch
                for n in battery
            ]
        )

    # DA market buy/sell logic
    for t in time_periods:
        model += e_da[t] == e_s_da[t] + e_b_da[t]
        model += e_s_da[t] <= e_da_max * J_s[t]
        model += e_b_da[t] >= -e_da_max * (1 - J_s[t])

    # Reserve/DA capacity (energy per 5-min interval in kWh)
    for t in time_periods:
        e_cap_bar = p_w_bar[t] * D + pulp.lpSum([DR_bar[n] * D * eta_dis for n in battery])
        # DA sales allowed only when J_s[t]=1, bounded by capacity
        model += e_s_da[t] <= e_cap_bar * J_s[t]

    # Reserve market conditions (energy per 5-min interval in kWh)
    for t in time_periods:
        e_cap_underline = p_w_underline[t] * D + pulp.lpSum(
            [DR_bar[n] * D * 0.1 * eta_dis for n in battery]
        )
        model += e_6sec[t] * call[t] == pulp.lpSum([e_6sec_dis[n][t] * eta_dis for n in battery])
        model += e_60sec[t] * call[t] == pulp.lpSum([e_60sec_dis[n][t] * eta_dis for n in battery])
        # Reserve delivery bound independent of DA sell toggle
        model += e_6sec[t] + e_60sec[t] <= e_cap_underline

    # Battery net energy over entire horizon (always connected)
    for n in battery:
        model += E_dem[n] == pulp.lpSum(
            [e_ch[n][t] / eta_ch - e_da_dis[n][t] - e_6sec_dis[n][t] - e_60sec_dis[n][t] for t in time_periods]
        )

    # Simultaneous charging/discharging prevention (power limits converted to energy per interval via D)
    for n in battery:
        for t in time_periods:
            model += e_da_dis[n][t] + e_6sec_dis[n][t] + e_60sec_dis[n][t] <= DR_bar[n] * D * (1 - u_ch[n][t])
            model += e_ch[n][t] <= CR_bar[n] * D * u_ch[n][t]

    # Battery state of charge (SoC) over entire horizon
    for n in battery:
        for t in time_periods:
            if t == 0:
                model += (
                    e_soc[n][t]
                    == E_0[n] + e_ch[n][t] * eta_ch - e_da_dis[n][t] - e_6sec_dis[n][t] - e_60sec_dis[n][t]
                )
            else:
                model += (
                    e_soc[n][t]
                    == e_soc[n][t - 1]
                    + e_ch[n][t] * eta_ch
                    - e_da_dis[n][t]
                    - e_6sec_dis[n][t]
                    - e_60sec_dis[n][t]
                )

    # Degradation cost calculation
    for n in battery:
        for t in time_periods:
            model += cost_deg[n][t] == lamda_bat * (e_da_dis[n][t] + e_6sec_dis[n][t] + e_60sec_dis[n][t])

    # Battery energy bounds over entire horizon
    for n in battery:
        for t in time_periods:
            model += e_soc[n][t] >= E_min[n]
            model += e_soc[n][t] <= E_max[n]

    # Non-negativity of variables enforced via bounds; no plug-in/out zeros since always plugged

    variables = {
        "e_da": e_da,
        "e_s_da": e_s_da,
        "e_b_da": e_b_da,
        "J_s": J_s,
        "e_6sec": e_6sec,
        "e_60sec": e_60sec,
        "e_ch": e_ch,
        "e_da_dis": e_da_dis,
        "e_6sec_dis": e_6sec_dis,
        "e_60sec_dis": e_60sec_dis,
        "u_ch": u_ch,
        "e_soc": e_soc,
        "cost_deg": cost_deg,
        "E_dem": E_dem,
    }

    return model, variables


def solve_model(model):
    """
    Solve the given PuLP model using the default solver.

    Returns
    -------
    int
        The model status after solving.
    """
    model.solve()
    return model.status