### this script uses solar_generator.py to generate the power profile for the generator

## we have some nodes

### we have some nodes, at each node there lives a generator
""" GFD0331	gracefield """
""" GYT0331	greytown """
""" HAY0111	haywards """
""" HAY0331	haywards """
""" MLG0111	melling """
""" MLG0331	melling """
""" MST0331	masterton """
""" PNI0331	pauatahanui """
""" TKR0331	takapu rd """
""" UHT0331	upper hutt """

## the nodes have the following lat and long coordinates

""" GFD0331	gracefield	Gracefield: -41.22, 174.92 """
""" GYT0331	greytown	Greytown: -41.08, 175.46 """
""" HAY0111	haywards	Haywards: -41.152, 174.981 (This is for the large Haywards substation) """
""" HAY0331	haywards	Haywards: -41.152, 174.981 (This is for the large Haywards substation) """
""" MLG0111	melling	Melling: -41.21, 174.90 """
""" MLG0331	melling	Melling: -41.21, 174.91 """
""" MST0331	masterton	Masterton: -40.96, 175.65 """
""" PNI0331	pauatahanui	Pauatahanui: -41.10, 174.92 """
""" TKR0331	takapu rd	Takapu Rd: -41.16, 174.87 (This is for the Takapu Road substation) """
""" UHT0331	upper hutt	Upper Hutt: -41.12, 175.07 """

### each generator is otherwise symmetric with the following parameters

""" peak_power_kw: 650.
simulation_date: start  at 2024-05-26T00:00:00.000+12:00 and end at 2024-11-13T23:55:00.000+13:00
latitude: taken from list above for each node.
longitude: taken from list above for each node.
intervals_per_hour: 12.
performance_ratio: 0.8. """

## we want to make a pandas dataframe with the following columns
""" node: the cod of the node in the list above (GFD0331, GYT0331, HAY0111, HAY0331, MLG0111, MLG0331, MST0331, PNI0331, TKR0331, UHT0331)
node name: the name of the node in the list above (Gracefield03, Greytown03, Haywards01, Haywards03, Melling01, Melling03, Masterton03, Pauatahanui03, Takapu Road03, Upper Hutt03)
tradinginterval: the datetime of the power generation, in this format: 2024-05-26T00:00:00.000+12:00.
power: the power generated by the generator.
"""
## then we want to save the dataframe to a csv file called "model_power_29102025.csv"

import pandas as pd
from datetime import timedelta
from solar_generator import calculate_solar_generation

# Simulation setup
TZ = "Pacific/Auckland"
PEAK_POWER_KW = 650.0
INTERVALS_PER_HOUR = 12 # 5 min intervals
PERFORMANCE_RATIO = 0.8 # performance ratio for the solar panels, arbitrary value

START = pd.Timestamp(2024, 5, 26, 0, 0, tz=TZ)
END = pd.Timestamp(2024, 11, 13, 23, 55, tz=TZ)

# Nodes: code, display name, latitude, longitude
NODES = {
    "GFD0331": {"name": "Gracefield03",   "lat": -41.22,  "lon": 174.92},
    "GYT0331": {"name": "Greytown03",     "lat": -41.08,  "lon": 175.46},
    "HAY0111": {"name": "Haywards01",     "lat": -41.152, "lon": 174.981},
    "HAY0331": {"name": "Haywards03",     "lat": -41.152, "lon": 174.981},
    "MLG0111": {"name": "Melling01",      "lat": -41.21,  "lon": 174.90},
    "MLG0331": {"name": "Melling03",      "lat": -41.21,  "lon": 174.91},
    "MST0331": {"name": "Masterton03",    "lat": -40.96,  "lon": 175.65},
    "PNI0331": {"name": "Pauatahanui03",  "lat": -41.10,  "lon": 174.92},
    "TKR0331": {"name": "Takapu Road03",  "lat": -41.16,  "lon": 174.87},
    "UHT0331": {"name": "Upper Hutt03",   "lat": -41.12,  "lon": 175.07},
}

def _date_iter(start_ts: pd.Timestamp, end_ts: pd.Timestamp):
    d = start_ts.date()
    end_d = end_ts.date()
    while d <= end_d:
        yield d
        d += timedelta(days=1)

def _generate_for_node(code: str, info: dict) -> pd.DataFrame:
    frames = []
    for day in _date_iter(START, END):
        s = calculate_solar_generation(
            peak_power_kw=PEAK_POWER_KW,
            simulation_date=day,
            latitude=info["lat"],
            longitude=info["lon"],
            intervals_per_hour=INTERVALS_PER_HOUR,
            performance_ratio=PERFORMANCE_RATIO,
        )
        s = s[(s.index >= START) & (s.index <= END)]
        if s.empty:
            continue
        df = s.to_frame(name="power").reset_index().rename(columns={"index": "tradinginterval"})
        df["node"] = code
        df["node name"] = info["name"]
        df = df[["node", "node name", "tradinginterval", "power"]]
        frames.append(df)
    if not frames:
        return pd.DataFrame(columns=["node", "node name", "tradinginterval", "power"])
    return pd.concat(frames, ignore_index=True)

def main():
    
    dfs = [_generate_for_node(code, info) for code, info in NODES.items()]
    out = pd.concat(dfs, ignore_index=True)
    # Format as ISO 8601 with milliseconds and timezone, e.g. 2024-05-26T00:00:00.000+12:00
    out["tradinginterval"] = out["tradinginterval"].apply(lambda ts: ts.isoformat(timespec="milliseconds"))
    out.to_csv("model_outputs_29102025/model_power_29102025.csv", index=False)

if __name__ == "__main__":
    main()