### this file contains the generator
### it takes values for lat, long, and time and returns how much power is generated by the solar panels

import numpy as np
import pandas as pd
from datetime import date, datetime, timezone
from astral.sun import sun
from astral import LocationInfo

### parameters
# peak_power_kw: The peak DC power rating of the solar array in kilowatts (kWp).
# simulation_date: The date for which to calculate the generation profile.
# latitude: The latitude of the solar farm.
# longitude: The longitude of the solar farm.
# intervals_per_hour: The number of time intervals per hour (e.g., 12 for 5-minute intervals).
# performance_ratio: A factor to account for real-world losses (e.g., from weather, temperature, inverter efficiency). Default is 0.8.
# returns: A pandas Series with a DateTimeIndex representing the 24-hour period
# and values representing the generated power in kW for each interval.

## function
# calculates the solar generation profile for a given day
# the function models generation as a sinusoidal curve between sunrise and
# sunset, peaking at the specified peak power
# the function applies a performance ratio to account for real-world losses
# the function returns a pandas Series with a DateTimeIndex representing the 24-hour period
# and values representing the generated power in kW for each interval.

## example usage
# calculate_solar_generation(
#     peak_power_kw=500,
#     simulation_date=date(2024, 12, 21),
#     latitude=-36.85,
#     longitude=174.76,
#     intervals_per_hour=12,
#     performance_ratio=0.8
# )

def calculate_solar_generation(
    peak_power_kw: float,
    simulation_date: date,
    latitude: float,
    longitude: float,
    intervals_per_hour: int = 12,
    performance_ratio: float = 0.8,
) -> pd.Series:
    """
    Calculates a realistic solar generation profile for a given day.

    The function models generation as a sinusoidal curve between sunrise and
    sunset, peaking at the specified peak power.

    Args:
        peak_power_kw: The peak DC power rating of the solar array in kilowatts (kWp).
        simulation_date: The date for which to calculate the generation profile.
        latitude: The latitude of the solar farm.
        longitude: The longitude of the solar farm.
        intervals_per_hour: The number of time intervals per hour (e.g., 12 for 5-minute intervals).
        performance_ratio: A factor to account for real-world losses (e.g., from
                           weather, temperature, inverter efficiency). Default is 0.8.

    Returns:
        A pandas Series with a DateTimeIndex representing the 24-hour period
        and values representing the generated power in kW for each interval.
    """
    # 1. Define the location for sunrise/sunset calculation
    # Using Auckland as a representative location for the North Island
    location = LocationInfo(
        "Auckland", "New Zealand", "Pacific/Auckland", latitude, longitude
    )

    # 2. Get sunrise and sunset times for the given date
    s = sun(location.observer, date=simulation_date, tzinfo=location.timezone)
    sunrise = s["sunrise"]
    sunset = s["sunset"]
    solar_noon = s["noon"]

    daylight_hours = (sunset - sunrise).total_seconds() / 3600.0

    if daylight_hours <= 0:
        # No daylight, return a series of zeros
        start_time = datetime.combine(simulation_date, datetime.min.time()).replace(tzinfo=timezone.utc)
        index = pd.to_datetime(pd.date_range(start=start_time, periods=24 * intervals_per_hour, freq=f"{60/intervals_per_hour}min"))
        return pd.Series(0, index=index)

    # 3. Create a time series for the entire day
    freq_minutes = 60 / intervals_per_hour
    timestamps = pd.date_range(
        start=simulation_date, periods=24 * intervals_per_hour, freq=f"{freq_minutes}min", tz=location.timezone
    )
    
    power_kw = pd.Series(0.0, index=timestamps)

    # 4. Calculate the power generation curve for daylight hours
    for ts in power_kw.index:
        if sunrise <= ts <= sunset:
            # Calculate the position of the current time within the daylight period (0 to pi)
            time_since_sunrise = (ts - sunrise).total_seconds()
            daylight_seconds = (sunset - sunrise).total_seconds()
            
            # Normalize time to a sine curve angle (0 at sunrise, pi/2 at noon, pi at sunset)
            angle = (time_since_sunrise / daylight_seconds) * np.pi
            
            # Calculate power using a sine function
            instant_power = peak_power_kw * np.sin(angle)
            
            # Apply performance ratio to account for real-world losses
            power_kw[ts] = instant_power * performance_ratio

    return power_kw


